[package]
name = "docker-tags"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1.0.44"
dotenv = "0.15.0"
semver = "1.0.4"

[profile.release]
lto = true
panic = "abort"
