[package]
name = "docker-tags"
version = "0.1.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
dotenv = "0.15.0"
semver = "1.0.3"

[profile.release]
lto = true
panic = "abort"
