name: Sample
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.2
        with:
          registries: |
            docker.io
            ghcr.io
            quay.io
      - name: Get the output tags
        run: echo "The tags are ${{ steps.docker_tags.outputs.tags }}"
