name: Sample
on: [push]
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1
      - name: Get the output tags
        run: echo "The tags are ${{ steps.docker_tags.outputs.tags }}"
