name: Sample
on: [push]
jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Tags Action
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1.0
      - name: Get the output tags
        run: echo "The tags are ${{ steps.docker_tags.outputs.tags }}"
